name: Lint and Format Python Code

on:
  push:
    branches: [ main ] # Adjust to your main branch name
  pull_request:
    branches: [ main ] # Adjust to your main branch name

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # or specify a specific version like '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
      - name: Lint with flake8
        run: |
          flake8 . --max-line-length 120 --ignore E501,W503
      - name: Format with black
        run: |
          black . --line-length 120
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Format code with black" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF} || echo "No changes to push"
